name: Vscode publish 

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read nvmrc
        run: nvmrc=$(cat .nvmrc)
      - uses: actions/setup-node@v1
        with:
          node-version: $nvmrc
      - run: npm ci
      - run: npm run test
      - run: npx semantic-release
        if: github.event_name == 'push'
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}      
      - run: npx vsce package
      - run: npx vsce publish -p "${{ secrets.AZURE_PERSONAL_TOKEN }}"
